services:
  php83_fpm:
    container_name: php83_fpm
    build:
      context: "./.docker"
      dockerfile: Dockerfile
    ports:
      - "9000:9000" # fpm
    volumes:
      - "./.:/var/www/html"

  http:
    container_name: http
    image: nginx
    ports:
      - "80:80" # http
    volumes:
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./.docker/nginx/http.conf:/etc/nginx/conf.d/default.conf"
      - "./.:/var/www/html"
    depends_on:
      - "php83_fpm"
