services:
  helpdesk_php:
    container_name: helpdesk_php
    build:
      context: "./.docker"
      dockerfile: Dockerfile
    ports:
      - "9000:9000" # fpm
    volumes:
      - "./.:/var/www/html"

  helpdesk_http:
    container_name: helpdesk_http
    image: nginx
    ports:
      - "80:80" # http
    volumes:
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./.docker/nginx/http.conf:/etc/nginx/conf.d/default.conf"
      - "./.:/var/www/html"
    depends_on:
      - "helpdesk_php"
